# Matrix Computation

## Inner Product

In [1]:
import numpy as np

In [2]:
# Vectors as 1D numpy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [3]:
print("a= ", a)
print("b= ", b)

a=  [1 2 3]
b=  [4 5 6]


In [4]:
print("\ninner:", np.inner(a, b))
print("dot:", np.dot(a, b))


inner: 32
dot: 32


## Dot Product

In [5]:
# Matrices as ndarray objects
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7], [8, 9, 10]])
print("a", type(a))
print(a)
print("\nb", type(b))
print(b)

a <class 'numpy.ndarray'>
[[1 2]
 [3 4]]

b <class 'numpy.ndarray'>
[[ 5  6  7]
 [ 8  9 10]]


In [6]:
print(np.dot(a, b))

[[21 24 27]
 [47 54 61]]


## Transpose

In [7]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print("a = ")
print(a)

a = 
[[1 2]
 [3 4]
 [5 6]]


In [8]:
print(np.transpose(a))

[[1 3 5]
 [2 4 6]]


## Trace

In [11]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])

In [12]:
print(a)

[[2 2 1]
 [1 3 1]
 [1 2 2]]


In [13]:
print("\nTrace:", a.trace())


Trace: 7


In [14]:
print("Trace:", sum(a.diagonal()))

Trace: 7


## Determinant

In [15]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])

In [16]:
print("a = ")
print(a)
det = np.linalg.det(a)

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]


In [17]:
print("\nDeterminant:", np.round(det))


Determinant: 5.0


## True inverse

In [18]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])

In [19]:
print("a = ")
print(a)
det = np.linalg.det(a)
print("\nDeterminant:", np.round(det))
inv = np.linalg.inv(a)
print("\nInverse of a = ")
print(inv)

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Determinant: 5.0

Inverse of a = 
[[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


## Pseudo inverse

## pinv()

In [20]:
a = np.array([[2, 8],
               [1, 4]])

In [21]:
det = np.linalg.det(a)
print("\nDeterminant:", np.round(det))


Determinant: 0.0


In [22]:
pinv = np.linalg.pinv(a)
print("\nPseudo Inverse of a = ")
print(pinv)


Pseudo Inverse of a = 
[[0.02352941 0.01176471]
 [0.09411765 0.04705882]]


## Flatten

In [23]:
a = np.arange(1, 10)
a.shape = (3, 3)

In [24]:
print("a = ")
print(a)

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print("\nAfter flattening")
print("------------------")
print(a.flatten())


After flattening
------------------
[1 2 3 4 5 6 7 8 9]


## Eigenvalues and eigenvectors

In [26]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]


In [27]:
w, v = np.linalg.eig(a)

In [28]:
print("\nEigenvalues:")
print(w)
print("\nEigenvectors:")
print(v)


Eigenvalues:
[5. 1. 1.]

Eigenvectors:
[[-0.57735027 -0.90453403  0.82529864]
 [-0.57735027  0.30151134 -0.52125218]
 [-0.57735027  0.30151134  0.21720572]]
